// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carbonService.proto

package grpc.newService.Carbon;

public interface CarbonDriveResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CarbonDriveResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 carbonOutput = 1;</code>
   */
  int getCarbonOutput();
}
