// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carbonService.proto

package grpc.newService.Carbon;

public interface CarbonFlightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CarbonFlightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 1 is just a tag/identifier, its not the contents of the variable
   * </pre>
   *
   * <code>int32 hoursInput = 1;</code>
   */
  int getHoursInput();
}
