// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carbonService.proto

package grpc.newService.Carbon;

public interface CarbonDriveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CarbonDriveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 milesInput = 1;</code>
   */
  int getMilesInput();

  /**
   * <code>int32 mpgInput = 2;</code>
   */
  int getMpgInput();
}
