// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carbonService.proto

package grpc.newService.Carbon;

/**
 * Protobuf type {@code CarbonFlightRequest}
 */
public  final class CarbonFlightRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CarbonFlightRequest)
    CarbonFlightRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CarbonFlightRequest.newBuilder() to construct.
  private CarbonFlightRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CarbonFlightRequest() {
    hoursInput_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CarbonFlightRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            hoursInput_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.newService.Carbon.CarbonServiceImpl.internal_static_CarbonFlightRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.newService.Carbon.CarbonServiceImpl.internal_static_CarbonFlightRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.newService.Carbon.CarbonFlightRequest.class, grpc.newService.Carbon.CarbonFlightRequest.Builder.class);
  }

  public static final int HOURSINPUT_FIELD_NUMBER = 1;
  private int hoursInput_;
  /**
   * <pre>
   * 1 is just a tag/identifier, its not the contents of the variable
   * </pre>
   *
   * <code>int32 hoursInput = 1;</code>
   */
  public int getHoursInput() {
    return hoursInput_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (hoursInput_ != 0) {
      output.writeInt32(1, hoursInput_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (hoursInput_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, hoursInput_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.newService.Carbon.CarbonFlightRequest)) {
      return super.equals(obj);
    }
    grpc.newService.Carbon.CarbonFlightRequest other = (grpc.newService.Carbon.CarbonFlightRequest) obj;

    boolean result = true;
    result = result && (getHoursInput()
        == other.getHoursInput());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HOURSINPUT_FIELD_NUMBER;
    hash = (53 * hash) + getHoursInput();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.newService.Carbon.CarbonFlightRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.newService.Carbon.CarbonFlightRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.newService.Carbon.CarbonFlightRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.newService.Carbon.CarbonFlightRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.newService.Carbon.CarbonFlightRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.newService.Carbon.CarbonFlightRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.newService.Carbon.CarbonFlightRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.newService.Carbon.CarbonFlightRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.newService.Carbon.CarbonFlightRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.newService.Carbon.CarbonFlightRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.newService.Carbon.CarbonFlightRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.newService.Carbon.CarbonFlightRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.newService.Carbon.CarbonFlightRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CarbonFlightRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CarbonFlightRequest)
      grpc.newService.Carbon.CarbonFlightRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.newService.Carbon.CarbonServiceImpl.internal_static_CarbonFlightRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.newService.Carbon.CarbonServiceImpl.internal_static_CarbonFlightRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.newService.Carbon.CarbonFlightRequest.class, grpc.newService.Carbon.CarbonFlightRequest.Builder.class);
    }

    // Construct using grpc.newService.Carbon.CarbonFlightRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      hoursInput_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.newService.Carbon.CarbonServiceImpl.internal_static_CarbonFlightRequest_descriptor;
    }

    @java.lang.Override
    public grpc.newService.Carbon.CarbonFlightRequest getDefaultInstanceForType() {
      return grpc.newService.Carbon.CarbonFlightRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.newService.Carbon.CarbonFlightRequest build() {
      grpc.newService.Carbon.CarbonFlightRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.newService.Carbon.CarbonFlightRequest buildPartial() {
      grpc.newService.Carbon.CarbonFlightRequest result = new grpc.newService.Carbon.CarbonFlightRequest(this);
      result.hoursInput_ = hoursInput_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.newService.Carbon.CarbonFlightRequest) {
        return mergeFrom((grpc.newService.Carbon.CarbonFlightRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.newService.Carbon.CarbonFlightRequest other) {
      if (other == grpc.newService.Carbon.CarbonFlightRequest.getDefaultInstance()) return this;
      if (other.getHoursInput() != 0) {
        setHoursInput(other.getHoursInput());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.newService.Carbon.CarbonFlightRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.newService.Carbon.CarbonFlightRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int hoursInput_ ;
    /**
     * <pre>
     * 1 is just a tag/identifier, its not the contents of the variable
     * </pre>
     *
     * <code>int32 hoursInput = 1;</code>
     */
    public int getHoursInput() {
      return hoursInput_;
    }
    /**
     * <pre>
     * 1 is just a tag/identifier, its not the contents of the variable
     * </pre>
     *
     * <code>int32 hoursInput = 1;</code>
     */
    public Builder setHoursInput(int value) {
      
      hoursInput_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 1 is just a tag/identifier, its not the contents of the variable
     * </pre>
     *
     * <code>int32 hoursInput = 1;</code>
     */
    public Builder clearHoursInput() {
      
      hoursInput_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CarbonFlightRequest)
  }

  // @@protoc_insertion_point(class_scope:CarbonFlightRequest)
  private static final grpc.newService.Carbon.CarbonFlightRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.newService.Carbon.CarbonFlightRequest();
  }

  public static grpc.newService.Carbon.CarbonFlightRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CarbonFlightRequest>
      PARSER = new com.google.protobuf.AbstractParser<CarbonFlightRequest>() {
    @java.lang.Override
    public CarbonFlightRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CarbonFlightRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CarbonFlightRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CarbonFlightRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.newService.Carbon.CarbonFlightRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

