// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carbonService.proto

package grpc.newService.Carbon;

public final class CarbonServiceImpl {
  private CarbonServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_carbonFlightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_carbonFlightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_carbonDriveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_carbonDriveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_carbonFlightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_carbonFlightResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_carbonDriveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_carbonDriveResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_containsString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_containsString_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newResponseInteger_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newResponseInteger_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023carbonService.proto\")\n\023carbonFlightReq" +
      "uest\022\022\n\nhoursInput\030\001 \001(\005\":\n\022carbonDriveR" +
      "equest\022\022\n\nmilesInput\030\001 \001(\005\022\020\n\010mpgInput\030\002" +
      " \001(\005\",\n\024carbonFlightResponse\022\024\n\014carbonOu" +
      "tput\030\001 \001(\t\"+\n\023carbonDriveResponse\022\024\n\014car" +
      "bonOutput\030\001 \001(\t\"%\n\016containsString\022\023\n\013fir" +
      "stString\030\001 \001(\t\"*\n\022newResponseInteger\022\024\n\014" +
      "firstInteger\030\001 \001(\0052\221\001\n\rcarbonService\022@\n\025" +
      "CalculateCarbonFlight\022\024.carbonFlightRequ" +
      "est\032\017.containsString\"\000\022>\n\024CalculateCarbo" +
      "nDrive\022\023.carbonDriveRequest\032\017.containsSt" +
      "ring\"\000B-\n\026grpc.newService.CarbonB\021Carbon" +
      "ServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_carbonFlightRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_carbonFlightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_carbonFlightRequest_descriptor,
        new java.lang.String[] { "HoursInput", });
    internal_static_carbonDriveRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_carbonDriveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_carbonDriveRequest_descriptor,
        new java.lang.String[] { "MilesInput", "MpgInput", });
    internal_static_carbonFlightResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_carbonFlightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_carbonFlightResponse_descriptor,
        new java.lang.String[] { "CarbonOutput", });
    internal_static_carbonDriveResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_carbonDriveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_carbonDriveResponse_descriptor,
        new java.lang.String[] { "CarbonOutput", });
    internal_static_containsString_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_containsString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_containsString_descriptor,
        new java.lang.String[] { "FirstString", });
    internal_static_newResponseInteger_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_newResponseInteger_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newResponseInteger_descriptor,
        new java.lang.String[] { "FirstInteger", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
