// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carbonService.proto

package grpc.newService.Carbon;

public final class CarbonServiceImpl {
  private CarbonServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CarbonFlightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CarbonFlightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CarbonDriveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CarbonDriveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CarbonFlightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CarbonFlightResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CarbonDriveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CarbonDriveResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023carbonService.proto\")\n\023CarbonFlightReq" +
      "uest\022\022\n\nhoursInput\030\001 \001(\005\":\n\022CarbonDriveR" +
      "equest\022\022\n\nmilesInput\030\001 \001(\005\022\020\n\010mpgInput\030\002" +
      " \001(\005\",\n\024CarbonFlightResponse\022\024\n\014carbonOu" +
      "tput\030\001 \001(\005\"+\n\023CarbonDriveResponse\022\024\n\014car" +
      "bonOutput\030\001 \001(\0052\235\001\n\rCarbonService\022F\n\025cal" +
      "culateCarbonFlight\022\024.CarbonFlightRequest" +
      "\032\025.CarbonFlightResponse\"\000\022D\n\024calculateCa" +
      "rbonDrive\022\023.CarbonDriveRequest\032\025.CarbonF" +
      "lightResponse\"\000B-\n\026grpc.newService.Carbo" +
      "nB\021CarbonServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CarbonFlightRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CarbonFlightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CarbonFlightRequest_descriptor,
        new java.lang.String[] { "HoursInput", });
    internal_static_CarbonDriveRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CarbonDriveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CarbonDriveRequest_descriptor,
        new java.lang.String[] { "MilesInput", "MpgInput", });
    internal_static_CarbonFlightResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CarbonFlightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CarbonFlightResponse_descriptor,
        new java.lang.String[] { "CarbonOutput", });
    internal_static_CarbonDriveResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CarbonDriveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CarbonDriveResponse_descriptor,
        new java.lang.String[] { "CarbonOutput", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
