// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radiationService.proto

package grpc.Radiation;

public interface levelsStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:levelsStream)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dangerousRegions = 1;</code>
   */
  java.lang.String getDangerousRegions();
  /**
   * <code>string dangerousRegions = 1;</code>
   */
  com.google.protobuf.ByteString
      getDangerousRegionsBytes();
}
