// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radiationService.proto

package grpc.Radiation;

public interface measurementsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:measurementsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
