// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radiationService.proto

package grpc.Radiation;

public interface radiationAlertOrBuilder extends
    // @@protoc_insertion_point(interface_extends:radiationAlert)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *string radiationAlertSet = 1;
   * </pre>
   *
   * <code>string radiationAlerts = 1;</code>
   */
  java.lang.String getRadiationAlerts();
  /**
   * <pre>
   *string radiationAlertSet = 1;
   * </pre>
   *
   * <code>string radiationAlerts = 1;</code>
   */
  com.google.protobuf.ByteString
      getRadiationAlertsBytes();
}
