// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radiationService.proto

package grpc.Radiation;

public interface radiationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:radiationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 received = 1;</code>
   */
  int getReceived();
}
