// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radiationService.proto

package grpc.Radiation;

public interface radiationMeasurementsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:radiationMeasurements)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 picocuries = 1;</code>
   */
  int getPicocuries();

  /**
   * <code>string clientID = 2;</code>
   */
  java.lang.String getClientID();
  /**
   * <code>string clientID = 2;</code>
   */
  com.google.protobuf.ByteString
      getClientIDBytes();
}
