// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radiationService.proto

package grpc.Radiation;

public interface radiationMeasurementsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:radiationMeasurements)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 picocuries = 1;</code>
   */
  int getPicocuries();
}
