// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radiationService.proto

package grpc.Radiation;

/**
 * Protobuf type {@code radiationAlert}
 */
public  final class radiationAlert extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:radiationAlert)
    radiationAlertOrBuilder {
private static final long serialVersionUID = 0L;
  // Use radiationAlert.newBuilder() to construct.
  private radiationAlert(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private radiationAlert() {
    radiationAlerts_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private radiationAlert(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            radiationAlerts_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.Radiation.RadiationServiceImpl.internal_static_radiationAlert_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.Radiation.RadiationServiceImpl.internal_static_radiationAlert_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.Radiation.radiationAlert.class, grpc.Radiation.radiationAlert.Builder.class);
  }

  public static final int RADIATIONALERTS_FIELD_NUMBER = 1;
  private volatile java.lang.Object radiationAlerts_;
  /**
   * <pre>
   *string radiationAlertSet = 1;
   * </pre>
   *
   * <code>string radiationAlerts = 1;</code>
   */
  public java.lang.String getRadiationAlerts() {
    java.lang.Object ref = radiationAlerts_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      radiationAlerts_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *string radiationAlertSet = 1;
   * </pre>
   *
   * <code>string radiationAlerts = 1;</code>
   */
  public com.google.protobuf.ByteString
      getRadiationAlertsBytes() {
    java.lang.Object ref = radiationAlerts_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      radiationAlerts_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRadiationAlertsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, radiationAlerts_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRadiationAlertsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, radiationAlerts_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.Radiation.radiationAlert)) {
      return super.equals(obj);
    }
    grpc.Radiation.radiationAlert other = (grpc.Radiation.radiationAlert) obj;

    boolean result = true;
    result = result && getRadiationAlerts()
        .equals(other.getRadiationAlerts());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RADIATIONALERTS_FIELD_NUMBER;
    hash = (53 * hash) + getRadiationAlerts().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.Radiation.radiationAlert parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.Radiation.radiationAlert parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.Radiation.radiationAlert parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.Radiation.radiationAlert parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.Radiation.radiationAlert parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.Radiation.radiationAlert parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.Radiation.radiationAlert parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.Radiation.radiationAlert parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.Radiation.radiationAlert parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.Radiation.radiationAlert parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.Radiation.radiationAlert parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.Radiation.radiationAlert parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.Radiation.radiationAlert prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code radiationAlert}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:radiationAlert)
      grpc.Radiation.radiationAlertOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.Radiation.RadiationServiceImpl.internal_static_radiationAlert_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.Radiation.RadiationServiceImpl.internal_static_radiationAlert_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.Radiation.radiationAlert.class, grpc.Radiation.radiationAlert.Builder.class);
    }

    // Construct using grpc.Radiation.radiationAlert.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      radiationAlerts_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.Radiation.RadiationServiceImpl.internal_static_radiationAlert_descriptor;
    }

    @java.lang.Override
    public grpc.Radiation.radiationAlert getDefaultInstanceForType() {
      return grpc.Radiation.radiationAlert.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.Radiation.radiationAlert build() {
      grpc.Radiation.radiationAlert result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.Radiation.radiationAlert buildPartial() {
      grpc.Radiation.radiationAlert result = new grpc.Radiation.radiationAlert(this);
      result.radiationAlerts_ = radiationAlerts_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.Radiation.radiationAlert) {
        return mergeFrom((grpc.Radiation.radiationAlert)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.Radiation.radiationAlert other) {
      if (other == grpc.Radiation.radiationAlert.getDefaultInstance()) return this;
      if (!other.getRadiationAlerts().isEmpty()) {
        radiationAlerts_ = other.radiationAlerts_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.Radiation.radiationAlert parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.Radiation.radiationAlert) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object radiationAlerts_ = "";
    /**
     * <pre>
     *string radiationAlertSet = 1;
     * </pre>
     *
     * <code>string radiationAlerts = 1;</code>
     */
    public java.lang.String getRadiationAlerts() {
      java.lang.Object ref = radiationAlerts_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        radiationAlerts_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *string radiationAlertSet = 1;
     * </pre>
     *
     * <code>string radiationAlerts = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRadiationAlertsBytes() {
      java.lang.Object ref = radiationAlerts_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        radiationAlerts_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *string radiationAlertSet = 1;
     * </pre>
     *
     * <code>string radiationAlerts = 1;</code>
     */
    public Builder setRadiationAlerts(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      radiationAlerts_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *string radiationAlertSet = 1;
     * </pre>
     *
     * <code>string radiationAlerts = 1;</code>
     */
    public Builder clearRadiationAlerts() {
      
      radiationAlerts_ = getDefaultInstance().getRadiationAlerts();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *string radiationAlertSet = 1;
     * </pre>
     *
     * <code>string radiationAlerts = 1;</code>
     */
    public Builder setRadiationAlertsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      radiationAlerts_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:radiationAlert)
  }

  // @@protoc_insertion_point(class_scope:radiationAlert)
  private static final grpc.Radiation.radiationAlert DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.Radiation.radiationAlert();
  }

  public static grpc.Radiation.radiationAlert getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<radiationAlert>
      PARSER = new com.google.protobuf.AbstractParser<radiationAlert>() {
    @java.lang.Override
    public radiationAlert parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new radiationAlert(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<radiationAlert> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<radiationAlert> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.Radiation.radiationAlert getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

