// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radiationService.proto

package grpc.Radiation;

public final class RadiationServiceImpl {
  private RadiationServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_radiationMeasurements_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_radiationMeasurements_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_measurementsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_measurementsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_radiationLevels_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_radiationLevels_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_levelsStream_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_levelsStream_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_requestRadiationAlerts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_requestRadiationAlerts_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_radiationAlert_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_radiationAlert_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026radiationService.proto\"+\n\025radiationMea" +
      "surements\022\022\n\npicocuries\030\001 \001(\005\"\'\n\024measure" +
      "mentsResponse\022\017\n\007message\030\001 \001(\t\"#\n\017radiat" +
      "ionLevels\022\020\n\010clientID\030\001 \001(\005\"(\n\014levelsStr" +
      "eam\022\030\n\020dangerousRegions\030\001 \001(\t\"+\n\026request" +
      "RadiationAlerts\022\021\n\tthreshold\030\001 \001(\005\"+\n\016ra" +
      "diationAlert\022\031\n\021radiationAlertSet\030\001 \001(\t2" +
      "\331\001\n\020radiationService\022D\n\017StreamRadiation\022" +
      "\026.radiationMeasurements\032\025.measurementsRe" +
      "sponse\"\000(\001\0229\n\022GetRadiationLevels\022\020.radia" +
      "tionLevels\032\r.levelsStream\"\0000\001\022D\n\024GetRadi" +
      "ationWarnings\022\027.requestRadiationAlerts\032\017" +
      ".radiationAlert\"\0000\001B(\n\016grpc.RadiationB\024R" +
      "adiationServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_radiationMeasurements_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_radiationMeasurements_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_radiationMeasurements_descriptor,
        new java.lang.String[] { "Picocuries", });
    internal_static_measurementsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_measurementsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_measurementsResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_radiationLevels_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_radiationLevels_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_radiationLevels_descriptor,
        new java.lang.String[] { "ClientID", });
    internal_static_levelsStream_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_levelsStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_levelsStream_descriptor,
        new java.lang.String[] { "DangerousRegions", });
    internal_static_requestRadiationAlerts_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_requestRadiationAlerts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_requestRadiationAlerts_descriptor,
        new java.lang.String[] { "Threshold", });
    internal_static_radiationAlert_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_radiationAlert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_radiationAlert_descriptor,
        new java.lang.String[] { "RadiationAlertSet", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
