// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radiationService.proto

package grpc.Radiation;

public interface radiationTrackOrBuilder extends
    // @@protoc_insertion_point(interface_extends:radiationTrack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 microsieverts = 1;</code>
   */
  int getMicrosieverts();
}
