// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radiationService.proto

package grpc.Radiation;

public final class RadiationServiceImpl {
  private RadiationServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_radiationTrack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_radiationTrack_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_radiationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_radiationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_radiationLevels_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_radiationLevels_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_levelsStream_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_levelsStream_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_requestRadiationAlerts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_requestRadiationAlerts_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_radiationAlert_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_radiationAlert_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_containsString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_containsString_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newRequestInteger_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newRequestInteger_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newResponseInteger_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newResponseInteger_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026radiationService.proto\"\'\n\016radiationTra" +
      "ck\022\025\n\rmicrosieverts\030\001 \001(\005\"%\n\021radiationRe" +
      "sponse\022\020\n\010received\030\001 \001(\005\"#\n\017radiationLev" +
      "els\022\020\n\010clientID\030\001 \001(\005\"(\n\014levelsStream\022\030\n" +
      "\020dangerousRegions\030\001 \001(\t\"*\n\026requestRadiat" +
      "ionAlerts\022\020\n\010clientID\030\001 \001(\005\"+\n\016radiation" +
      "Alert\022\031\n\021radiationAlertSet\030\001 \001(\t\"%\n\016cont" +
      "ainsString\022\023\n\013firstString\030\001 \001(\t\")\n\021newRe" +
      "questInteger\022\024\n\014firstInteger\030\001 \001(\005\"*\n\022ne" +
      "wResponseInteger\022\024\n\014firstInteger\030\001 \001(\0052\222" +
      "\002\n\020radiationService\022:\n\017StreamRadiation\022\022" +
      ".newRequestInteger\032\017.containsString\"\000(\001\022" +
      "9\n\022GetRadiationLevels\022\020.radiationLevels\032" +
      "\r.levelsStream\"\0000\001\022D\n\024GetRadiationWarnin" +
      "gs\022\027.requestRadiationAlerts\032\017.radiationA" +
      "lert\"\0000\001\022A\n\031SendStringClientStreaming\022\017." +
      "containsString\032\017.containsString\"\000(\001B(\n\016g" +
      "rpc.RadiationB\024RadiationServiceImplP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_radiationTrack_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_radiationTrack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_radiationTrack_descriptor,
        new java.lang.String[] { "Microsieverts", });
    internal_static_radiationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_radiationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_radiationResponse_descriptor,
        new java.lang.String[] { "Received", });
    internal_static_radiationLevels_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_radiationLevels_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_radiationLevels_descriptor,
        new java.lang.String[] { "ClientID", });
    internal_static_levelsStream_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_levelsStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_levelsStream_descriptor,
        new java.lang.String[] { "DangerousRegions", });
    internal_static_requestRadiationAlerts_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_requestRadiationAlerts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_requestRadiationAlerts_descriptor,
        new java.lang.String[] { "ClientID", });
    internal_static_radiationAlert_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_radiationAlert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_radiationAlert_descriptor,
        new java.lang.String[] { "RadiationAlertSet", });
    internal_static_containsString_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_containsString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_containsString_descriptor,
        new java.lang.String[] { "FirstString", });
    internal_static_newRequestInteger_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_newRequestInteger_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newRequestInteger_descriptor,
        new java.lang.String[] { "FirstInteger", });
    internal_static_newResponseInteger_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_newResponseInteger_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newResponseInteger_descriptor,
        new java.lang.String[] { "FirstInteger", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
