// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radiationService.proto

package grpc.Radiation;

public interface requestRadiationAlertsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:requestRadiationAlerts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 clientID = 1;</code>
   */
  int getClientID();
}
