// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radiationService.proto

package grpc.Radiation;

/**
 * <pre>
 * if a level of radiation rises above a certain threshold
 * an alert is sent to the requesting client
 * </pre>
 *
 * Protobuf type {@code requestRadiationAlerts}
 */
public  final class requestRadiationAlerts extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:requestRadiationAlerts)
    requestRadiationAlertsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use requestRadiationAlerts.newBuilder() to construct.
  private requestRadiationAlerts(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private requestRadiationAlerts() {
    clientID_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private requestRadiationAlerts(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            clientID_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.Radiation.RadiationServiceImpl.internal_static_requestRadiationAlerts_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.Radiation.RadiationServiceImpl.internal_static_requestRadiationAlerts_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.Radiation.requestRadiationAlerts.class, grpc.Radiation.requestRadiationAlerts.Builder.class);
  }

  public static final int CLIENTID_FIELD_NUMBER = 1;
  private int clientID_;
  /**
   * <code>int32 clientID = 1;</code>
   */
  public int getClientID() {
    return clientID_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (clientID_ != 0) {
      output.writeInt32(1, clientID_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (clientID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, clientID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.Radiation.requestRadiationAlerts)) {
      return super.equals(obj);
    }
    grpc.Radiation.requestRadiationAlerts other = (grpc.Radiation.requestRadiationAlerts) obj;

    boolean result = true;
    result = result && (getClientID()
        == other.getClientID());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
    hash = (53 * hash) + getClientID();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.Radiation.requestRadiationAlerts parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.Radiation.requestRadiationAlerts parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.Radiation.requestRadiationAlerts parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.Radiation.requestRadiationAlerts parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.Radiation.requestRadiationAlerts parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.Radiation.requestRadiationAlerts parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.Radiation.requestRadiationAlerts parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.Radiation.requestRadiationAlerts parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.Radiation.requestRadiationAlerts parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.Radiation.requestRadiationAlerts parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.Radiation.requestRadiationAlerts parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.Radiation.requestRadiationAlerts parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.Radiation.requestRadiationAlerts prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * if a level of radiation rises above a certain threshold
   * an alert is sent to the requesting client
   * </pre>
   *
   * Protobuf type {@code requestRadiationAlerts}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:requestRadiationAlerts)
      grpc.Radiation.requestRadiationAlertsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.Radiation.RadiationServiceImpl.internal_static_requestRadiationAlerts_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.Radiation.RadiationServiceImpl.internal_static_requestRadiationAlerts_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.Radiation.requestRadiationAlerts.class, grpc.Radiation.requestRadiationAlerts.Builder.class);
    }

    // Construct using grpc.Radiation.requestRadiationAlerts.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      clientID_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.Radiation.RadiationServiceImpl.internal_static_requestRadiationAlerts_descriptor;
    }

    @java.lang.Override
    public grpc.Radiation.requestRadiationAlerts getDefaultInstanceForType() {
      return grpc.Radiation.requestRadiationAlerts.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.Radiation.requestRadiationAlerts build() {
      grpc.Radiation.requestRadiationAlerts result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.Radiation.requestRadiationAlerts buildPartial() {
      grpc.Radiation.requestRadiationAlerts result = new grpc.Radiation.requestRadiationAlerts(this);
      result.clientID_ = clientID_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.Radiation.requestRadiationAlerts) {
        return mergeFrom((grpc.Radiation.requestRadiationAlerts)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.Radiation.requestRadiationAlerts other) {
      if (other == grpc.Radiation.requestRadiationAlerts.getDefaultInstance()) return this;
      if (other.getClientID() != 0) {
        setClientID(other.getClientID());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.Radiation.requestRadiationAlerts parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.Radiation.requestRadiationAlerts) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int clientID_ ;
    /**
     * <code>int32 clientID = 1;</code>
     */
    public int getClientID() {
      return clientID_;
    }
    /**
     * <code>int32 clientID = 1;</code>
     */
    public Builder setClientID(int value) {
      
      clientID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 clientID = 1;</code>
     */
    public Builder clearClientID() {
      
      clientID_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:requestRadiationAlerts)
  }

  // @@protoc_insertion_point(class_scope:requestRadiationAlerts)
  private static final grpc.Radiation.requestRadiationAlerts DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.Radiation.requestRadiationAlerts();
  }

  public static grpc.Radiation.requestRadiationAlerts getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<requestRadiationAlerts>
      PARSER = new com.google.protobuf.AbstractParser<requestRadiationAlerts>() {
    @java.lang.Override
    public requestRadiationAlerts parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new requestRadiationAlerts(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<requestRadiationAlerts> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<requestRadiationAlerts> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.Radiation.requestRadiationAlerts getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

