// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutionService.proto

package grpc.pollution;

public interface airPollutionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airPollution)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 carbon = 1;</code>
   */
  int getCarbon();
}
