// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutionService.proto

package grpc.pollution;

public interface allDeviceStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:allDeviceStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool statusRequested = 1;</code>
   */
  boolean getStatusRequested();
}
