// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutionService.proto

package grpc.pollution;

public interface allDeviceStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:allDeviceStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float overallDeviceHealth = 1;</code>
   */
  float getOverallDeviceHealth();
}
