// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutionService.proto

package grpc.pollution;

public interface deviceStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deviceStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the response of the health of the given IoT device
   * </pre>
   *
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * the response of the health of the given IoT device
   * </pre>
   *
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
