// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutionService.proto

package grpc.pollution;

public interface deviceStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deviceStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the id of the IoT device to be checked.
   * </pre>
   *
   * <code>string statusRequestedID = 1;</code>
   */
  java.lang.String getStatusRequestedID();
  /**
   * <pre>
   * the id of the IoT device to be checked.
   * </pre>
   *
   * <code>string statusRequestedID = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusRequestedIDBytes();
}
