// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutionService.proto

package grpc.pollution;

/**
 * <pre>
 * GetDeviceStatus
 * This gets the health status of a specific
 * IoT device which is returned as a float
 * out of 100%.
 * </pre>
 *
 * Protobuf type {@code deviceStatusRequest}
 */
public  final class deviceStatusRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:deviceStatusRequest)
    deviceStatusRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use deviceStatusRequest.newBuilder() to construct.
  private deviceStatusRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private deviceStatusRequest() {
    statusRequestedID_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private deviceStatusRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            statusRequestedID_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.pollution.PollutionServiceImpl.internal_static_deviceStatusRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.pollution.PollutionServiceImpl.internal_static_deviceStatusRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.pollution.deviceStatusRequest.class, grpc.pollution.deviceStatusRequest.Builder.class);
  }

  public static final int STATUSREQUESTEDID_FIELD_NUMBER = 1;
  private volatile java.lang.Object statusRequestedID_;
  /**
   * <pre>
   * the id of the IoT device to be checked.
   * </pre>
   *
   * <code>string statusRequestedID = 1;</code>
   */
  public java.lang.String getStatusRequestedID() {
    java.lang.Object ref = statusRequestedID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      statusRequestedID_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * the id of the IoT device to be checked.
   * </pre>
   *
   * <code>string statusRequestedID = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStatusRequestedIDBytes() {
    java.lang.Object ref = statusRequestedID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      statusRequestedID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStatusRequestedIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, statusRequestedID_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStatusRequestedIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, statusRequestedID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.pollution.deviceStatusRequest)) {
      return super.equals(obj);
    }
    grpc.pollution.deviceStatusRequest other = (grpc.pollution.deviceStatusRequest) obj;

    boolean result = true;
    result = result && getStatusRequestedID()
        .equals(other.getStatusRequestedID());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUSREQUESTEDID_FIELD_NUMBER;
    hash = (53 * hash) + getStatusRequestedID().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.pollution.deviceStatusRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.pollution.deviceStatusRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.pollution.deviceStatusRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.pollution.deviceStatusRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.pollution.deviceStatusRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.pollution.deviceStatusRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.pollution.deviceStatusRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.pollution.deviceStatusRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.pollution.deviceStatusRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.pollution.deviceStatusRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.pollution.deviceStatusRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.pollution.deviceStatusRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.pollution.deviceStatusRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * GetDeviceStatus
   * This gets the health status of a specific
   * IoT device which is returned as a float
   * out of 100%.
   * </pre>
   *
   * Protobuf type {@code deviceStatusRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:deviceStatusRequest)
      grpc.pollution.deviceStatusRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.pollution.PollutionServiceImpl.internal_static_deviceStatusRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.pollution.PollutionServiceImpl.internal_static_deviceStatusRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.pollution.deviceStatusRequest.class, grpc.pollution.deviceStatusRequest.Builder.class);
    }

    // Construct using grpc.pollution.deviceStatusRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      statusRequestedID_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.pollution.PollutionServiceImpl.internal_static_deviceStatusRequest_descriptor;
    }

    @java.lang.Override
    public grpc.pollution.deviceStatusRequest getDefaultInstanceForType() {
      return grpc.pollution.deviceStatusRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.pollution.deviceStatusRequest build() {
      grpc.pollution.deviceStatusRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.pollution.deviceStatusRequest buildPartial() {
      grpc.pollution.deviceStatusRequest result = new grpc.pollution.deviceStatusRequest(this);
      result.statusRequestedID_ = statusRequestedID_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.pollution.deviceStatusRequest) {
        return mergeFrom((grpc.pollution.deviceStatusRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.pollution.deviceStatusRequest other) {
      if (other == grpc.pollution.deviceStatusRequest.getDefaultInstance()) return this;
      if (!other.getStatusRequestedID().isEmpty()) {
        statusRequestedID_ = other.statusRequestedID_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.pollution.deviceStatusRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.pollution.deviceStatusRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object statusRequestedID_ = "";
    /**
     * <pre>
     * the id of the IoT device to be checked.
     * </pre>
     *
     * <code>string statusRequestedID = 1;</code>
     */
    public java.lang.String getStatusRequestedID() {
      java.lang.Object ref = statusRequestedID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        statusRequestedID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * the id of the IoT device to be checked.
     * </pre>
     *
     * <code>string statusRequestedID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStatusRequestedIDBytes() {
      java.lang.Object ref = statusRequestedID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statusRequestedID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * the id of the IoT device to be checked.
     * </pre>
     *
     * <code>string statusRequestedID = 1;</code>
     */
    public Builder setStatusRequestedID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      statusRequestedID_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the id of the IoT device to be checked.
     * </pre>
     *
     * <code>string statusRequestedID = 1;</code>
     */
    public Builder clearStatusRequestedID() {
      
      statusRequestedID_ = getDefaultInstance().getStatusRequestedID();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the id of the IoT device to be checked.
     * </pre>
     *
     * <code>string statusRequestedID = 1;</code>
     */
    public Builder setStatusRequestedIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      statusRequestedID_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:deviceStatusRequest)
  }

  // @@protoc_insertion_point(class_scope:deviceStatusRequest)
  private static final grpc.pollution.deviceStatusRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.pollution.deviceStatusRequest();
  }

  public static grpc.pollution.deviceStatusRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<deviceStatusRequest>
      PARSER = new com.google.protobuf.AbstractParser<deviceStatusRequest>() {
    @java.lang.Override
    public deviceStatusRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new deviceStatusRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<deviceStatusRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<deviceStatusRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.pollution.deviceStatusRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

