// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutionService.proto

package grpc.pollution;

public interface locationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:locationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 longitude = 1;</code>
   */
  int getLongitude();

  /**
   * <code>int32 latitude = 2;</code>
   */
  int getLatitude();
}
