// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutionService.proto

package grpc.pollution;

public interface newResponseIntegerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:newResponseInteger)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 firstInteger = 1;</code>
   */
  int getFirstInteger();
}
