// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutionService.proto

package grpc.pollution;

public final class PollutionServiceImpl {
  private PollutionServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airPollution_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airPollution_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_locationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_locationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_regionalPollutionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_regionalPollutionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deviceStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deviceStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_deviceStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_deviceStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_allDeviceStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_allDeviceStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_allDeviceStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_allDeviceStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026pollutionService.proto\"*\n\014airPollution" +
      "\022\016\n\006carbon\030\001 \001(\005\022\n\n\002id\030\002 \001(\t\"\034\n\010response" +
      "\022\020\n\010received\030\001 \001(\t\"6\n\017locationRequest\022\021\n" +
      "\tlongitude\030\001 \001(\005\022\020\n\010latitude\030\002 \001(\005\"3\n\031re" +
      "gionalPollutionResponse\022\026\n\016regionalStatu" +
      "s\030\001 \001(\t\"0\n\023deviceStatusRequest\022\031\n\021status" +
      "RequestedID\030\001 \001(\t\"&\n\024deviceStatusRespons" +
      "e\022\016\n\006status\030\001 \001(\t\"1\n\026allDeviceStatusRequ" +
      "est\022\027\n\017statusRequested\030\001 \001(\010\"6\n\027allDevic" +
      "eStatusResponse\022\033\n\023overallDeviceHealth\030\001" +
      " \001(\0022\234\002\n\020pollutionService\022/\n\017StreamPollu" +
      "tion\022\r.airPollution\032\t.response\"\000(\001\022J\n\024Ge" +
      "tLocalAirPollution\022\020.locationRequest\032\032.r" +
      "egionalPollutionResponse\"\000(\0010\001\022>\n\017GetDev" +
      "iceStatus\022\024.deviceStatusRequest\032\025.device" +
      "StatusResponse\022K\n\022GetAllDeviceStatus\022\027.a" +
      "llDeviceStatusRequest\032\030.allDeviceStatusR" +
      "esponse\"\0000\001B(\n\016grpc.pollutionB\024Pollution" +
      "ServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_airPollution_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_airPollution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airPollution_descriptor,
        new java.lang.String[] { "Carbon", "Id", });
    internal_static_response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_response_descriptor,
        new java.lang.String[] { "Received", });
    internal_static_locationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_locationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_locationRequest_descriptor,
        new java.lang.String[] { "Longitude", "Latitude", });
    internal_static_regionalPollutionResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_regionalPollutionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_regionalPollutionResponse_descriptor,
        new java.lang.String[] { "RegionalStatus", });
    internal_static_deviceStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_deviceStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deviceStatusRequest_descriptor,
        new java.lang.String[] { "StatusRequestedID", });
    internal_static_deviceStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_deviceStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_deviceStatusResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_allDeviceStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_allDeviceStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_allDeviceStatusRequest_descriptor,
        new java.lang.String[] { "StatusRequested", });
    internal_static_allDeviceStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_allDeviceStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_allDeviceStatusResponse_descriptor,
        new java.lang.String[] { "OverallDeviceHealth", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
