// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutionService.proto

package grpc.pollution;

public interface regionalPollutionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:regionalPollutionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string regionalStatus = 1;</code>
   */
  java.lang.String getRegionalStatus();
  /**
   * <code>string regionalStatus = 1;</code>
   */
  com.google.protobuf.ByteString
      getRegionalStatusBytes();
}
