// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollutionService.proto

package grpc.pollution;

public interface responseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string received = 1;</code>
   */
  java.lang.String getReceived();
  /**
   * <code>string received = 1;</code>
   */
  com.google.protobuf.ByteString
      getReceivedBytes();
}
