// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carbonService.proto

package grpc.Carbon;

public interface carbonDriveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:carbonDriveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the number of miles
   * </pre>
   *
   * <code>int32 milesInput = 1;</code>
   */
  int getMilesInput();

  /**
   * <pre>
   * the miles per gallon
   * </pre>
   *
   * <code>int32 mpgInput = 2;</code>
   */
  int getMpgInput();

  /**
   * <pre>
   * petrol or diesel
   * </pre>
   *
   * <code>string fuelType = 3;</code>
   */
  java.lang.String getFuelType();
  /**
   * <pre>
   * petrol or diesel
   * </pre>
   *
   * <code>string fuelType = 3;</code>
   */
  com.google.protobuf.ByteString
      getFuelTypeBytes();
}
