// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carbonService.proto

package grpc.Carbon;

public interface carbonFlightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:carbonFlightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string carbonOutput = 1;</code>
   */
  java.lang.String getCarbonOutput();
  /**
   * <code>string carbonOutput = 1;</code>
   */
  com.google.protobuf.ByteString
      getCarbonOutputBytes();
}
