// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carbonService.proto

package grpc.Carbon;

public final class CarbonServiceImpl {
  private CarbonServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_carbonFlightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_carbonFlightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_carbonDriveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_carbonDriveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_responseString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_responseString_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023carbonService.proto\")\n\023carbonFlightReq" +
      "uest\022\022\n\nhoursInput\030\001 \001(\005\"L\n\022carbonDriveR" +
      "equest\022\022\n\nmilesInput\030\001 \001(\005\022\020\n\010mpgInput\030\002" +
      " \001(\005\022\020\n\010fuelType\030\003 \001(\t\"!\n\016responseString" +
      "\022\017\n\007message\030\001 \001(\t2\221\001\n\rcarbonService\022@\n\025C" +
      "alculateCarbonFlight\022\024.carbonFlightReque" +
      "st\032\017.responseString\"\000\022>\n\024CalculateCarbon" +
      "Drive\022\023.carbonDriveRequest\032\017.responseStr" +
      "ing\"\000B\"\n\013grpc.CarbonB\021CarbonServiceImplP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_carbonFlightRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_carbonFlightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_carbonFlightRequest_descriptor,
        new java.lang.String[] { "HoursInput", });
    internal_static_carbonDriveRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_carbonDriveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_carbonDriveRequest_descriptor,
        new java.lang.String[] { "MilesInput", "MpgInput", "FuelType", });
    internal_static_responseString_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_responseString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_responseString_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
